/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.servlet;

import jakarta.servlet.ServletException;
import jakarta.servlet.http.*;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * @author afnan
 * This is third way to create a servlet before this we also discuss two methods to create servlet
 * in 'FristServlet' & 'SecondServlet' class
 * In this method we are going to create servlet by extending HttpServlet class
 * HttpServelt Extends GenericServlet class and override all 5 methods
 * so we don't need to override any method
 * we use HttpServlet class if get or post method is going to be used in html
 * http servlet has doget() and doPost method which we need to override to get and post any request from html
 */
public class ThirdServlet extends HttpServlet{

    @Override
    public void doPost (HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        // this is post method
    }

    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        //this is get method body
        resp.setContentType("text/html");
        PrintWriter out = resp.getWriter();
        out.print("<h2> This My third servlet using HttpServlet class and this text is generated by doGet method</h2>");
    }
    
}
